# Generated by Django 4.2.17 on 2024-12-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('shop_owner', 'Shop Owner'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
