# Generated by Django 4.2.17 on 2024-12-07 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ration_app', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopOwnerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('aadhar_image', models.ImageField(upload_to='aadhar_images/')),
                ('shop_name', models.CharField(max_length=100)),
                ('shop_address', models.TextField()),
                ('shop_license_number', models.CharField(max_length=50)),
                ('license_image', models.ImageField(upload_to='license_images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
