# Generated by Django 4.2.17 on 2024-12-07 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration_app', '0004_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.CharField(max_length=100),
        ),
    ]
