# Generated by Django 4.2.17 on 2024-12-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration_app', '0007_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_filled',
            field=models.BooleanField(default=False),
        ),
    ]
