# Generated by Django 4.2.17 on 2024-12-07 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ration_app', '0008_userprofile_profile_filled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_filled',
        ),
    ]
