# Generated by Django 4.2.17 on 2024-12-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration_app', '0012_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='product',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='quantity',
        ),
        migrations.AddField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='products',
            field=models.ManyToManyField(to='ration_app.product'),
        ),
        migrations.AddField(
            model_name='booking',
            name='ration_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='ration_cards/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='ration_card_number',
            field=models.CharField(default='00000000', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(),
        ),
    ]
