# Generated by Django 4.2.17 on 2024-12-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration_app', '0013_remove_booking_product_remove_booking_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='ration_card_image',
            field=models.ImageField(default='ration_cards/default.jpg', upload_to='ration_cards/'),
        ),
    ]
