# Generated by Django 4.2.17 on 2024-12-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration_app', '0014_alter_booking_ration_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
