# Generated by Django 4.2.17 on 2024-12-09 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ration_app', '0015_customuser_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_approved',
        ),
    ]
