# Generated by Django 4.2.17 on 2024-12-09 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration_app', '0016_remove_customuser_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopownerdetails',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
