# Generated by Django 4.2.17 on 2024-12-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration_app', '0017_shopownerdetails_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopownerdetails',
            name='approved',
        ),
        migrations.AddField(
            model_name='shopownerdetails',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
