# Generated by Django 4.2.17 on 2024-12-09 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ration_app', '0018_remove_shopownerdetails_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ration_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ration_app.shopownerdetails'),
        ),
    ]
