# Generated by Django 4.2.17 on 2024-12-09 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ration_app', '0019_booking_ration_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shop_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='ration_app.shopownerdetails'),
        ),
    ]
