# Generated by Django 4.2.17 on 2024-12-10 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ration_app', '0021_remove_product_shop_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shop_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ration_app.shopownerdetails'),
        ),
    ]
