# Generated by Django 4.2.17 on 2024-12-13 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ration_app', '0024_rationcardapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rationcardapplication',
            name='id_proofs',
        ),
        migrations.AlterField(
            model_name='rationcardapplication',
            name='house_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='rationcardapplication',
            name='master_of_the_house',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rationcardapplication',
            name='punchayath_or_corporation',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='IDProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='id_proofs/')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_proofs', to='ration_app.rationcardapplication')),
            ],
        ),
    ]
