# Generated by Django 4.2.17 on 2024-12-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration_app', '0024_rationcardapplications_idproofs'),
    ]

    operations = [
        migrations.AddField(
            model_name='rationcardapplications',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
